# Copyright 2024 Szűcs Krisztián
# SPDX-License-Identifier: Apache-2.0

"""Coverage-guided fuzzing with libFuzzer, and the replay of what it found.

A **target** is a file `fuzz/<name>.mojo` defining

    def fuzz_one(data: Span[UInt8, _]) raises

Raising is the correct answer to malformed input; an abort, a signal or a
sanitizer report is a bug.  The harness holds nothing else -- the libFuzzer
entry points and the replay driver are generated here, so the rules every
target must follow live in one place.

Two builds of the same harness:

- **fuzzing** (`Fuzzer`): `mojo build --emit llvm-bitcode`, then clang adds
  SanitizerCoverage and AddressSanitizer and links libFuzzer.  `mojo build` has
  no coverage flag, which is why clang is involved at all.  The bitcode is
  emitted with `--sanitize address` so its functions carry the
  `sanitize_address` attribute -- without it clang's pass instruments nothing
  -- and `LLVMFuzzerInitialize` routes Mojo's heap through libc, the allocator
  AddressSanitizer replaces.  Each half alone reports no heap overflow at all.
- **replay** (`Replay`): one ordinary `mojo build` of every target behind a
  `main()`, run once per committed input in a fresh process.  Needs no clang,
  so it runs wherever the tests do, and it is also what proves every harness
  still compiles.

The committed corpus is `fuzz/corpus/<target>/`, with an `expected.toml` per
target giving each file's verdict: `accept` and `reject` for inputs the reader
must decode or refuse, `crash` for a reproducer of a known, unfixed bug.  A
crash entry that stops crashing fails the replay too -- the bug was fixed, and
the entry's verdict should move with it.
"""

import os
import platform
import re
import shutil
import sys
import tomllib
from dataclasses import dataclass
from pathlib import Path

from .mojo import BuildOptions, write_if_changed

#: What a target file has to define.
ENTRY = re.compile(r"^def\s+fuzz_one\s*\(", re.MULTILINE)

#: The verdicts `expected.toml` may give an entry.
VERDICTS = ("accept", "reject", "crash")

#: Every built artifact carries the platform it is for, so a host and a
#: container working in one tree never run each other's binaries.
PLATFORM = f"{sys.platform}-{platform.machine()}"


# ---------------------------------------------------------------------------
# Targets
# ---------------------------------------------------------------------------


class Targets:
    """The harnesses under `fuzz/`, and where each one's working files go."""

    def __init__(self, repo):
        self._repo = repo

    @property
    def directory(self):
        return self._repo.fuzz_dir

    def names(self):
        """Every target, sorted: each `fuzz/*.mojo` that defines `fuzz_one`.

        A shared module under `fuzz/` defines no entry point and so is not a
        target -- which is what lets harnesses import a helper from beside
        them.
        """
        return sorted(
            path.stem
            for path in self.directory.glob("*.mojo")
            if ENTRY.search(path.read_text())
        )

    def resolve(self, name):
        """*name* if it is a target, else a `ValueError` listing the targets."""
        names = self.names()
        if name not in names:
            raise ValueError(
                f"no fuzz target {name!r}; targets are: {', '.join(names)}"
            )
        return name

    def harness(self, name):
        return self.directory / f"{name}.mojo"

    def corpus(self, name):
        """The committed regression corpus."""
        return self.directory / "corpus" / name

    def work(self, name):
        """Untracked: the binary, seeds, the growing corpus and crashes."""
        return self._repo.fuzz_work_dir / name


# ---------------------------------------------------------------------------
# Generated Mojo
# ---------------------------------------------------------------------------


ENTRY_TEMPLATE = """\
# Generated by devkit/fuzzing.py -- do not edit.
from std.ffi import external_call

from {module} import fuzz_one


@export
def LLVMFuzzerInitialize(
    argc: Pointer[Int32, MutUntrackedOrigin],
    argv: Pointer[UInt8, MutUntrackedOrigin],
) abi("C") -> Int32:
    # Mojo allocates through its own tcmalloc, whose blocks carry no redzones;
    # libc's allocator is the one AddressSanitizer replaces.
    external_call["KGEN_CompilerRT_SetAsanAllocators", NoneType]()
    return 0


@export
def LLVMFuzzerTestOneInput(
    data: Pointer[UInt8, MutUntrackedOrigin], size: Int
) abi("C") -> Int32:
    try:
        fuzz_one(Span(unsafe_ptr=data, length=size))
    except:
        pass
    return 0
"""

REPLAY_TEMPLATE = """\
# Generated by devkit/fuzzing.py -- do not edit.
from std.sys import argv

{imports}


def main() raises:
    var args = argv()
    if len(args) != 3:
        raise Error("usage: replay TARGET FILE")
    var target = String(args[1])
    var data: List[UInt8]
    with open(String(args[2]), "r") as f:
        data = f.read_bytes()
    try:
{dispatch}
        else:
            raise Error("unknown fuzz target: " + target)
    except e:
        print("reject:", e)
        return
    print("accept")
"""


def entry_source(name):
    """The libFuzzer entry points around target *name*."""
    return ENTRY_TEMPLATE.format(module=name)


def replay_source(names):
    """One `main()` dispatching to every target in *names*."""
    imports = "\n".join(f"from {n} import fuzz_one as {n}" for n in names)
    arms = []
    for i, n in enumerate(names):
        keyword = "if" if i == 0 else "elif"
        arms.append(f'        {keyword} target == "{n}":\n            {n}(Span(data))')
    return REPLAY_TEMPLATE.format(imports=imports, dispatch="\n".join(arms))


# ---------------------------------------------------------------------------
# clang
# ---------------------------------------------------------------------------


class BitcodeVersionError(RuntimeError):
    """clang is older than the LLVM that wrote Mojo's bitcode."""


class Clang:
    """The clang that instruments Mojo's bitcode and links libFuzzer.

    It has to read bitcode from Mojo's LLVM, which runs ahead of every
    released toolchain -- Xcode's clang cannot, and says only "Unknown
    attribute kind".  The `fuzz` pixi environment carries a conda-forge clang
    that can; outside it, a Homebrew LLVM is the fallback on macOS.
    """

    HOMEBREW = Path("/opt/homebrew/opt/llvm/bin/clang")

    #: The Mojo runtime a harness's bitcode calls into.
    MOJO_LIBS = (
        "KGENCompilerRTShared",
        "AsyncRTMojoBindings",
        "AsyncRTRuntimeGlobals",
        "MSupportGlobals",
    )

    #: How LLVM reports bitcode from a newer producer.
    UNREADABLE = re.compile(r"Producer: '([^']+)' Reader: '([^']+)'")

    def __init__(self, path, runner):
        self.path = Path(path)
        self._runner = runner

    def __repr__(self):
        return f"Clang({str(self.path)!r})"

    @classmethod
    def locate(cls, runner, env=None):
        """The environment's clang, else Homebrew's on macOS; None if neither."""
        env = os.environ if env is None else env
        prefix = env.get("CONDA_PREFIX")
        candidates = [Path(prefix) / "bin" / "clang"] if prefix else []
        if sys.platform == "darwin":
            candidates.append(cls.HOMEBREW)
        for candidate in candidates:
            if candidate.exists():
                return cls(candidate, runner)
        return None

    @staticmethod
    def mojo_lib_dir(env=None):
        """Where the Mojo runtime libraries are: the pixi environment's lib."""
        env = os.environ if env is None else env
        return Path(env.get("CONDA_PREFIX") or sys.prefix) / "lib"

    def link_flags(self, lib_dir):
        flags = ["-L", str(lib_dir), *(f"-l{lib}" for lib in self.MOJO_LIBS)]
        flags += [f"-Wl,-rpath,{lib_dir}"]
        if sys.platform != "darwin":
            flags += ["-lm"]
        return flags

    def link_fuzzer(self, bitcode, out, lib_dir, label):
        """Instrument *bitcode* and link it against libFuzzer.

        Raises `BitcodeVersionError` when clang cannot read the bitcode at all,
        since every other failure message would bury that one line.
        """
        result = self._runner.run(
            [
                self.path,
                "-O1",
                "-g",
                "-fsanitize=fuzzer,address",
                # Mojo stamps the host triple's OS version; clang's is the
                # one that matters for the link, and saying so is noise.
                "-Wno-override-module",
                bitcode,
                *self.link_flags(lib_dir),
                "-o",
                out,
            ],
            label,
        )
        if not result.ok:
            found = self.UNREADABLE.search(result.output)
            if found:
                raise BitcodeVersionError(
                    f"{self.path} cannot read Mojo's bitcode: it was written by "
                    f"{found.group(1)} and this clang is {found.group(2)}. "
                    "Use the `fuzz` pixi environment, whose clang tracks Mojo's "
                    "LLVM (`pixi run -e fuzz ...`)."
                )
        return result


# ---------------------------------------------------------------------------
# Building and running libFuzzer
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class RunOptions:
    """One fuzzing session's libFuzzer flags."""

    seconds: int = 120
    jobs: int = 0
    max_len: int = 1 << 16
    timeout: int = 10
    rss_limit_mb: int = 2048

    def flags(self, artifacts):
        flags = [
            f"-max_total_time={self.seconds}",
            f"-max_len={self.max_len}",
            f"-timeout={self.timeout}",
            f"-rss_limit_mb={self.rss_limit_mb}",
            f"-artifact_prefix={artifacts}/",
            "-print_final_stats=1",
        ]
        if self.jobs:
            # Fork mode survives a crash and keeps going, which is what a
            # session over a reader with known bugs needs to find the rest.
            flags += [f"-fork={self.jobs}", "-ignore_crashes=1", "-ignore_ooms=1"]
            flags += ["-ignore_timeouts=1"]
        return flags


class Fuzzer:
    """Builds a target into a libFuzzer binary and runs it."""

    def __init__(self, repo, toolchain, clang, runner):
        self._repo = repo
        self._targets = Targets(repo)
        self._mojo = toolchain
        self._clang = clang
        self._runner = runner

    def binary(self, name):
        return self._targets.work(name) / f"fuzz_{name}-{PLATFORM}"

    def build(self, name):
        """Emit *name*'s bitcode and link it; returns the binary."""
        work = self._targets.work(name)
        entry = write_if_changed(work / "entry.mojo", entry_source(name))
        bitcode = work / f"{name}-{PLATFORM}.bc"
        result = self._mojo.emit_bitcode(
            entry, bitcode, BuildOptions.for_fuzzing(), f"emitting {name} bitcode"
        )
        if self._mojo.reports_errors(result):
            raise RuntimeError(result.failure(f"{name}: bitcode emission failed"))
        result = self._clang.link_fuzzer(
            bitcode,
            self.binary(name),
            Clang.mojo_lib_dir(),
            f"linking fuzz_{name}",
        )
        if not result.ok:
            raise RuntimeError(result.failure(f"{name}: clang failed"))
        return self.binary(name)

    def seed(self, name):
        """Write the seed corpus; returns the directory and how many seeds."""
        directory = self._targets.work(name) / "seeds"
        directory.mkdir(parents=True, exist_ok=True)
        count = 0
        for label, data in SEEDS.get(name, lambda: [])():
            (directory / label).write_bytes(data)
            count += 1
        return directory, count

    def run(self, name, options, extra=()):
        """A session over the working corpus, seeded from `seed`.

        New inputs go to the working corpus, the first directory; the seeds
        and the committed corpus's `accept` entries are read only.
        """
        work = self._targets.work(name)
        corpus = work / "corpus"
        artifacts = work / "artifacts"
        for directory in (corpus, artifacts):
            directory.mkdir(parents=True, exist_ok=True)
        seeds, _ = self.seed(name)
        dirs = [corpus, seeds]
        anchors = self.anchor_dir(name)
        if anchors is not None:
            dirs.append(anchors)
        return self._runner.run(
            [self.binary(name), *options.flags(artifacts), *extra, *dirs],
            f"fuzzing {name} for {options.seconds}s",
            env=self.environment(),
        )

    def anchor_dir(self, name):
        """The committed inputs that must be accepted, staged where libFuzzer
        can read them as a corpus -- crash entries would end the session on
        its first input."""
        expected = Expectations.load(self._targets.corpus(name))
        accepted = [e for e in expected.entries if e.verdict == "accept"]
        if not accepted:
            return None
        directory = self._targets.work(name) / "anchors"
        shutil.rmtree(directory, ignore_errors=True)
        directory.mkdir(parents=True)
        for entry in accepted:
            shutil.copyfile(entry.path, directory / entry.path.name)
        return directory

    def execute(self, name, inputs, extra=()):
        """Run the libFuzzer binary over *inputs* once each, no mutation."""
        return self._runner.run(
            [self.binary(name), *extra, *inputs],
            f"running fuzz_{name}",
            env=self.environment(),
        )

    def minimize(self, name, crash, out, runs=10000):
        """The smallest input that still crashes the way *crash* does."""
        return self._runner.run(
            [
                self.binary(name),
                "-minimize_crash=1",
                f"-runs={runs}",
                f"-exact_artifact_path={out}",
                crash,
            ],
            f"minimizing {Path(crash).name}",
            env=self.environment(),
        )

    @staticmethod
    def environment():
        """AddressSanitizer settings for every run.

        `detect_leaks=0`: a harness that raises leaves what it allocated to
        Mojo's destructors, and a leak report would bury the crash that
        mattered.  `abort_on_error=1` makes a report a signal, which is what
        fork mode counts.

        `MARROW_DYLIB_DIR` names where the codec libraries are.  On Linux the
        binary's runpath finds them -- until GCC's ASAN runtime intercepts
        `dlopen`, which makes the loader search the runtime's paths instead.
        """
        env = dict(os.environ)
        env.setdefault("ASAN_OPTIONS", "detect_leaks=0:abort_on_error=1")
        env.setdefault("MARROW_DYLIB_DIR", str(Clang.mojo_lib_dir(env)))
        return env


# ---------------------------------------------------------------------------
# Crash signatures
# ---------------------------------------------------------------------------


#: Where a failed `debug_assert` points: `At: ./marrow/ipc.mojo:2007:30:`.
ASSERT_AT = re.compile(r"At: \.?/?(marrow/[\w/]+\.mojo:\d+)")
#: A symbolized frame in marrow: `in marrow::ipc::_BatchDecoder::read_array(...) ipc.mojo:2018`.
MARROW_FRAME = re.compile(
    r" in (marrow::[\w:]+)[^\n]*?(?: (\w+\.mojo(?::\d+)?))?$", re.M
)
#: The sanitizer's one-line verdict: `SUMMARY: AddressSanitizer: heap-buffer-overflow ...`.
SANITIZER = re.compile(r"SUMMARY: (AddressSanitizer|libFuzzer): ([\w-]+)")
MESSAGE = re.compile(r"(?:Assert Error|ABORT):?\s*([^\n]+)")


def signature(output):
    """What bucket a crash belongs in: the failure, and where in marrow.

    The failure is the sanitizer's kind or the abort message, with numbers
    blanked so two inputs overflowing by different amounts share a bucket.
    The location is the failed assertion's line, else the first stack frame
    inside marrow -- the code the input actually broke.
    """
    what = "unknown"
    found = SANITIZER.search(output)
    message = MESSAGE.search(output)
    if found and found.group(1) == "AddressSanitizer":
        what = f"asan: {found.group(2)}"
    elif message:
        what = re.sub(r"-?\d+", "N", message.group(1).strip())[:120]
    elif found:
        what = f"libfuzzer: {found.group(2)}"
    at = ASSERT_AT.search(output)
    frame = MARROW_FRAME.search(output)
    if at and not (found and found.group(1) == "AddressSanitizer"):
        where = at.group(1)
    elif frame:
        where = " ".join(part for part in frame.groups() if part)
    else:
        where = "no marrow frame"
    return f"{what} @ {where}"


def executions(log):
    """How many inputs a session ran, from libFuzzer's status lines.

    Fork mode reports `exec/s: 0` on every line, so the count is read from the
    last `#N` line instead and divided by the session's own wall time.
    """
    counts = re.findall(r"^#(\d+)", log, re.M)
    return int(counts[-1]) if counts else 0


def triage(binary, crashes, limit=0, jobs=8):
    """`{signature: [crash, ...]}` for *crashes* run through *binary*.

    Each run is a fraction of a second, so they go through `subprocess`
    directly and in parallel rather than through a progress display per input.
    Smallest first, so with a `limit` the reproducers kept are the small ones.
    """
    import subprocess
    from concurrent.futures import ThreadPoolExecutor

    crashes = sorted(crashes, key=lambda p: (p.stat().st_size, p.name))
    if limit:
        crashes = crashes[:limit]

    def one(crash):
        try:
            done = subprocess.run(
                [str(binary), str(crash)],
                capture_output=True,
                text=True,
                errors="replace",
                timeout=60,
                env=Fuzzer.environment(),
            )
            return crash, signature(done.stderr + done.stdout)
        except subprocess.TimeoutExpired:
            return crash, "timeout @ replay"

    buckets = {}
    with ThreadPoolExecutor(jobs) as pool:
        for crash, key in pool.map(one, crashes):
            buckets.setdefault(key, []).append(crash)
    return buckets


# ---------------------------------------------------------------------------
# The committed corpus and its replay
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class Entry:
    """One committed input and what replaying it must do."""

    path: Path
    verdict: str
    bug: str = ""
    match: str = ""
    note: str = ""
    sanitizer: str = ""

    @property
    def name(self):
        return self.path.name

    def skip_reason(self, asan):
        """Why a replay without a sanitizer cannot judge this entry, or None.

        A read a few bytes past an allocation corrupts nothing a plain build
        notices, so such a reproducer is accepted there; only an ASAN replay
        tells it from a fixed bug.
        """
        if self.sanitizer == "address" and not asan:
            return (
                f"{self.name} crashes only under AddressSanitizer; replay with --asan"
            )
        return None


class Expectations:
    """`fuzz/corpus/<target>/expected.toml`: every input's verdict.

        ["b1-slice-body.arrows"]
        verdict = "crash"
        bug = "B1"
        match = "out of bounds"

    `match` is a substring the crash output has to contain, so a reproducer
    that starts failing somewhere else is reported rather than counted.
    `sanitizer = "address"` marks a reproducer only an ASAN replay catches.
    """

    FILE = "expected.toml"

    def __init__(self, directory, entries):
        self.directory = Path(directory)
        self.entries = entries

    @classmethod
    def load(cls, directory):
        directory = Path(directory)
        manifest = directory / cls.FILE
        table = tomllib.loads(manifest.read_text()) if manifest.exists() else {}
        entries = []
        for name, spec in table.items():
            verdict = spec.get("verdict", "")
            if verdict not in VERDICTS:
                raise ValueError(
                    f"{manifest}: {name!r} has verdict {verdict!r}; "
                    f"expected one of {', '.join(VERDICTS)}"
                )
            entries.append(
                Entry(
                    directory / name,
                    verdict,
                    spec.get("bug", ""),
                    spec.get("match", ""),
                    spec.get("note", ""),
                    spec.get("sanitizer", ""),
                )
            )
        return cls(directory, entries)

    def problems(self):
        """Files with no verdict, and verdicts naming no file."""
        listed = {entry.name for entry in self.entries}
        present = (
            {p.name for p in self.directory.iterdir() if p.name != self.FILE}
            if self.directory.exists()
            else set()
        )
        found = [f"{name}: no verdict in {self.FILE}" for name in present - listed]
        found += [
            f"{name}: listed in {self.FILE} but missing" for name in listed - present
        ]
        return sorted(found)


@dataclass(frozen=True)
class Outcome:
    """What one replayed input did."""

    verdict: str
    output: str

    @classmethod
    def of(cls, result):
        if result.ok and "accept" in result.stdout.split():
            return cls("accept", result.output)
        if result.ok and result.stdout.startswith("reject:"):
            return cls("reject", result.output)
        return cls("crash", result.output)


def judge(entry, outcome):
    """None if *outcome* is what *entry* expects, else why not."""
    if outcome.verdict == entry.verdict:
        if (
            entry.verdict == "crash"
            and entry.match
            and entry.match not in outcome.output
        ):
            return (
                f"{entry.name}: still crashes, but no longer with {entry.match!r} -- "
                f"now: {signature(outcome.output)}\n{outcome.output[-4000:]}"
            )
        return None
    if entry.verdict == "crash":
        return (
            f"{entry.name}: expected a crash ({entry.bug or 'unnamed bug'}) and got "
            f"{outcome.verdict} -- if the bug is fixed, change its verdict in "
            f"{Expectations.FILE}\n{outcome.output[-2000:]}"
        )
    return (
        f"{entry.name}: expected {entry.verdict}, got {outcome.verdict}"
        f" ({signature(outcome.output) if outcome.verdict == 'crash' else ''})\n"
        f"{outcome.output[-4000:]}"
    )


class Replay:
    """Every target behind one `main()`, and each committed input through it.

    With `asan` the driver is built against the AddressSanitizer runtime (the
    `asan` pixi environment), which is the only replay that can judge an entry
    marked `sanitizer = "address"`.
    """

    def __init__(self, repo, toolchain, asan=False):
        self._repo = repo
        self._targets = Targets(repo)
        self._mojo = toolchain
        self.asan = asan

    @property
    def binary(self):
        flavor = "replay-asan" if self.asan else "replay"
        return self._repo.fuzz_work_dir / "replay" / f"{flavor}-{PLATFORM}"

    def build(self):
        """Compile the replay driver; returns the result, `ok` or not.

        This is also the compile check for `fuzz/`: `precompile` stops at
        `marrow/`, so a harness nothing builds would rot unnoticed.
        """
        source = write_if_changed(
            self._repo.fuzz_work_dir / "replay" / "replay.mojo",
            replay_source(self._targets.names()),
        )
        return self._mojo.build(
            source,
            self.binary,
            BuildOptions.for_fuzz_replay(asan=self.asan),
            "building fuzz replay",
        )

    def entries(self, names=None):
        """`(target, entry)` for every committed input."""
        for name in names or self._targets.names():
            for entry in Expectations.load(self._targets.corpus(name)).entries:
                yield name, entry

    def run(self, target, entry):
        result = self._mojo.execute(
            self.binary,
            [target, entry.path],
            f"replaying {target}/{entry.name}",
            env=Fuzzer.environment(),
        )
        return Outcome.of(result)


# ---------------------------------------------------------------------------
# Seeds
# ---------------------------------------------------------------------------


def _sample_table(rows=64):
    """One table over the layouts the readers decode: primitives, booleans,
    strings, lists, structs and dictionaries, each with nulls."""
    import pyarrow as pa

    def nulls(values):
        return [None if i % 7 == 3 else v for i, v in enumerate(values)]

    return pa.table(
        {
            "i64": pa.array(nulls(list(range(rows))), pa.int64()),
            "i32": pa.array(nulls([i * 3 - 50 for i in range(rows)]), pa.int32()),
            "f64": pa.array(nulls([i / 4 for i in range(rows)]), pa.float64()),
            "flag": pa.array(nulls([i % 3 == 0 for i in range(rows)]), pa.bool_()),
            "s": pa.array(nulls([f"v{i % 11}" * (i % 4) for i in range(rows)])),
            "l": pa.array(
                nulls([list(range(i % 5)) for i in range(rows)]), pa.list_(pa.int32())
            ),
            "st": pa.array(
                nulls([{"a": i, "b": str(i)} for i in range(rows)]),
                pa.struct([("a", pa.int16()), ("b", pa.string())]),
            ),
            "d": pa.array(
                nulls([f"k{i % 3}" for i in range(rows)])
            ).dictionary_encode(),
        }
    )


def _tables():
    """`(label, table)` -- the whole sample, each column alone, and empty."""
    table = _sample_table()
    yield "all", table
    yield "empty", table.slice(0, 0)
    for name in table.column_names:
        yield name, table.select([name]).slice(0, 9)


def ipc_stream_seeds():
    import pyarrow as pa

    for label, table in _tables():
        sink = pa.BufferOutputStream()
        with pa.ipc.new_stream(sink, table.schema) as writer:
            for batch in table.to_batches(max_chunksize=16) or [table]:
                writer.write(batch)
        yield f"{label}.arrows", sink.getvalue().to_pybytes()


def ipc_file_seeds():
    import pyarrow as pa

    for label, table in _tables():
        sink = pa.BufferOutputStream()
        with pa.ipc.new_file(sink, table.schema) as writer:
            for batch in table.to_batches(max_chunksize=16) or [table]:
                writer.write(batch)
        yield f"{label}.arrow", sink.getvalue().to_pybytes()


def parquet_seeds():
    """Every codec, both data page versions, the non-default encodings, and a
    page index over several small pages."""
    import pyarrow as pa
    import pyarrow.parquet as pq

    table = _sample_table()
    flat = table.select(["i64", "i32", "f64", "flag", "s"])
    variants = [
        (codec, {"compression": codec})
        for codec in ("none", "snappy", "zstd", "gzip", "brotli", "lz4")
    ]
    variants += [
        ("v2", {"data_page_version": "2.0", "compression": "zstd"}),
        ("plain", {"use_dictionary": False}),
        ("index", {"write_page_index": True, "data_page_size": 128}),
        ("stats-off", {"write_statistics": False}),
    ]
    for label, kwargs in variants:
        sink = pa.BufferOutputStream()
        pq.write_table(table, sink, **kwargs)
        yield f"{label}.parquet", sink.getvalue().to_pybytes()
    sink = pa.BufferOutputStream()
    pq.write_table(
        flat,
        sink,
        use_dictionary=False,
        column_encoding={
            "i64": "DELTA_BINARY_PACKED",
            "i32": "DELTA_BINARY_PACKED",
            "f64": "BYTE_STREAM_SPLIT",
            "s": "DELTA_BYTE_ARRAY",
        },
        write_page_index=True,
        data_page_size=64,
    )
    yield "delta.parquet", sink.getvalue().to_pybytes()
    sink = pa.BufferOutputStream()
    pq.write_table(
        flat.select(["s"]),
        sink,
        use_dictionary=False,
        column_encoding={"s": "DELTA_LENGTH_BYTE_ARRAY"},
    )
    yield "delta-length.parquet", sink.getvalue().to_pybytes()


def _payloads():
    yield "empty", b""
    yield "text", b"the quick brown fox jumps over the lazy dog " * 20
    yield "runs", b"a" * 1000 + b"b" * 1000
    yield "mixed", bytes(range(256)) * 4
    yield "ints", b"".join(i.to_bytes(4, "little") for i in range(512))


def snappy_seeds():
    import pyarrow as pa

    for label, data in _payloads():
        yield f"{label}.bin", pa.compress(data, codec="snappy", asbytes=True)


#: `Compression` codes against the pyarrow codec that writes their format;
#: code 0 is the uncompressed copy.  Order and codes match `fuzz/codecs.mojo`.
CODECS = {
    0: None,
    1: "snappy",
    2: "gzip",
    4: "brotli",
    5: "lz4_raw",
    6: "zstd",
    7: "lz4_raw",
}


def codecs_seeds():
    import pyarrow as pa

    for selector, (code, codec) in enumerate(CODECS.items()):
        for label, data in _payloads():
            packed = (
                data if codec is None else pa.compress(data, codec=codec, asbytes=True)
            )
            header = bytes([selector]) + len(data).to_bytes(3, "little")
            yield f"{code}-{label}.bin", header + packed


SEEDS = {
    "ipc_stream": ipc_stream_seeds,
    "ipc_file": ipc_file_seeds,
    "parquet_metadata": parquet_seeds,
    "parquet_read": parquet_seeds,
    "parquet_page_index": parquet_seeds,
    "snappy": snappy_seeds,
    "codecs": codecs_seeds,
}
