name: Marrow Test

on:
  - push
  - pull_request
  - workflow_call

jobs:
  test:
    strategy:
      matrix:
        include:
          - { target: linux-64, os: ubuntu-latest }
          - { target: osx-arm64, os: macos-latest }
          - { target: linux-aarch64, os: ubuntu-24.04-arm }
      fail-fast: false

    runs-on: ${{ matrix.os }}
    timeout-minutes: 5

    defaults:
      run:
        shell: bash

    env:
      MODULAR_HOME: "/home/runner/.modular"
      FORCE_COLOR: "1"
      PYTEST_ADDOPTS: "--color=yes"
    steps:
    - name: Checkout repo
      uses: actions/checkout@v6
    - uses: prefix-dev/setup-pixi@v0.9.4
      with:
        cache: true
        cache-write: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
        frozen: true
    - name: checks
      run: pixi run fmt_check
    - name: tests
      run: |
        pixi run test --no-gpu
        pixi run package
